# Explore contente of redis: docker run --rm -ti redis /bin/sh
# ../redis-server ./redis.conf
# /usr/local/bin
# docker-entrypoint.sh  gosu  redis-benchmark  redis-check-aof  redis-check-rdb  redis-cli  redis-sentinel  redis-server
# Cluster
version: '3'

services:

    redis1:
        image: redis:6.0.10-alpine
        restart: always
        entrypoint: ["redis-server", "/conf/redis.conf"]
        volumes:
            - ./conf/redis1.conf:/conf/redis.conf
        network_mode: host
#        ports:
#          - 6379:6379
#          - 16379:16379
      
    redis2:
        image: redis:6.0.10-alpine
        restart: always
        entrypoint: ["redis-server", "/conf/redis.conf"]
        volumes:
            - ./conf/redis2.conf:/conf/redis.conf
        network_mode: host
#        ports:
#          - 6380:6380
#          - 16380:16380

    redis3:
        image: redis:6.0.10-alpine
        restart: always
        entrypoint: ["redis-server", "/conf/redis.conf"]
        volumes:
            - ./conf/redis3.conf:/conf/redis.conf
        network_mode: host       
#        ports:
#          - 6380:6380
#          - 16380:16380
            


#    config:
#        # redis-cli --cluster create 127.0.0.1:7000 127.0.0.1:7001 \
#        # 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005 \
#        # --cluster-replicas 1
#        #"--no-auth-warning
#        #entrypoint: ["redis-cli", "--cluster", "create", "$(hostname -i redis1):7000", "$(hostname -i redis2):7000", "$hostname -i redis3):7000", "--cluster-replicas", "0",  "--verbose", "--cluster-yes"]
#        entrypoint: redis-cli --cluster create \$(hostname -i redis1):7000 \$(hostname -i redis2):7000 \$hostname -i redis3):7000 --cluster-replicas 0 --verbose --cluster-yes
#        image: redis:6.0.10-alpine
#        #entrypoint: ["/bin/sh", "-c", "/script/enable-cluster.sh"]
#        #entrypoint: ["ls", "-latr", "/script"]
#        depends_on:
#            - redis1
#            - redis2
#            - redis3
#        volumes:
#            - ./script:/script
            

    
  