version: '3'

services:

  redis:
    image: redis:6.0.10-alpine
    container_name: redis
    restart: always

  gui-redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  gui-rebrow:
    container_name: rebrow
    image: marian/rebrow
    ports:
        - "8082:5001"
    depends_on:
        - redis        
      
